package-lock.json
package.json

Njiandan1255 zot gui

---

src/components/Explore.jsx
src/components/ImageDetails.jsx
src/components/SignIn.js

Cleanup static data and handlers

---

package-lock.json
package.json

Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>
```release-note
```

fix dependabot alerts

---

Makefile
package-lock.json

add Makefile

---

src/components/Home.jsx

Closes issue #27 
Updated homepage styling to be more inline with mocks
```release-note
- Updated Home component styling
```

Updated homepage styling

---

src/components/RepoDetails.jsx
src/components/Tags.jsx
src/pages/RepoPage.jsx

Closes issue #28 
Updated styling for Repository details page to be more inline with mockups
```release-note
- Updated RepoDetails component styling
- Updated Tags component title
- Updated RepoPage component styling
- 
```

Repo details page updated styling

---

src/assets/Profile_button_placeholder.svg
src/components/Header.jsx
src/pages/RepoPage.jsx

Header component updated layout to be more inline with mocks
```release-note
- Added user placeholder image
- Updated Header component layout
- Fixed an issue with header inside of RepoPage component
```

Update header component layout to be more inline with mocks

---

Makefile

cleanup
Closes #57 
Updates make scripts to exclude dev dependency audit.
Fixed build script syntax

Updated makefile to emit dev dependencies, fixed build script

---

src/components/PreviewCard.jsx
src/components/RepoCard.jsx

Closes Issue #26 
Update RepoCard, PreviewCard styling to be more inline with mocks
```release-note
- Updated RepoCard component styles
- Updated PreviewCard component styles
```

Updated repo card design to be more inline with mocks

---

src/components/Explore.jsx
src/components/ExploreHeader.jsx
src/components/FilterCard.jsx
src/components/Header.jsx
src/components/Home.jsx
src/components/RepoDetails.jsx
src/components/RepoDetailsMetadata.jsx
src/components/SignIn.jsx
src/components/Tags.jsx
src/components/TermsOfService.jsx
src/pages/ExplorePage.jsx
src/pages/HomePage.jsx

cleanup
This is a follow-up PR to comments made on PR #42 regarding the usage of static px measurements.
Changed all measurements to be in relative units.

Eliminated all static pixel measurements in favor or relative units

---

package.json
src/App.js
src/App.test.js
src/__tests__/LoginPage/LoginPage.test.js
src/__tests__/LoginPage/SignIn.test.js
src/components/SignIn.jsx
src/components/SignInPresentation.jsx
src/pages/LoginPage.jsx

cleanup
Closes #53 
Adds testing for login related components and features
no

Test suite for login page related components

---

src/__tests__/Explore/Explore.test.js
src/__tests__/Explore/ExplorePage.test.js
src/components/Explore.jsx
src/pages/ExplorePage.jsx

cleanup
Closes #55 
Adds testing for explore page related components and features
no

Test suite for explore page related components

---

src/__tests__/RepoPage/Repo.test.js
src/__tests__/RepoPage/RepoPage.test.js
src/__tests__/RepoPage/Tags.test.js
src/__tests__/Shared/PreviewCard.test.js
src/__tests__/Shared/RepoCard.test.js
src/components/ExploreHeader.jsx
src/components/PreviewCard.jsx
src/components/RepoCard.jsx
src/components/RepoDetails.jsx
src/components/Tags.jsx
src/pages/RepoPage.jsx

cleanup
Closes #56 
Adds testing for repo details and shared components and features
no

Test suite for repo details and shared components

---

src/components/SignInPresentation.jsx

```release-note
- modified login page background
```

Added gradient light background to sign in page

---

src/components/RepoCard.jsx

Fixed newest tag display

---

src/host.js

Host config fix for production build

Production build host config

---

src/api.js
src/components/RepoDetails.jsx
src/components/TagDetails.jsx
src/components/Tags.jsx

Signed-off-by: Amelia-Maria Breda <ameliamaria.breda@dxc.com>
Closes #84
Added details from API in ui
```release-note
```

Added API data that was ready on 29th of September

---

src/__tests__/TagPage/TagDetails.test.js
src/api.js
src/components/DependsOn.jsx
src/components/HistoryLayers.jsx
src/components/RepoDetails.jsx
src/components/TagDetails.jsx
src/components/Tags.jsx
src/utilities/transform.js

Closes #74 
Added the layers for image page
```release-note
```

Layers tab features

---

src/App.js
src/__tests__/Explore/Explore.test.js
src/__tests__/Explore/FilterCard.test.js
src/__tests__/RepoPage/RepoPage.test.js
src/__tests__/TagPage/TagPage.test.js
src/api.js
src/components/Explore.jsx
src/components/FilterCard.jsx
src/components/Header.jsx
src/components/RepoCard.jsx
src/components/SearchSuggestion.jsx
src/pages/ExplorePage.jsx
src/pages/HomePage.jsx
src/pages/RepoPage.jsx
src/pages/TagPage.jsx
src/utilities/filterConstants.js

feature
Closes #95 
Implements filter feature on explore page.
```release-note
- Implemented filter feature in explore component
- Refactored explore to use the GlobalSearch query as opposed to RepoListWithNewestTag
- Refactored data global state variable usage
- Updated tests
```

feat(explore): Implemented filter feature

---

src/__tests__/RepoPage/Tags.test.js
src/components/RepoDetails.jsx
src/components/RepoDetailsMetadata.jsx
src/components/Tags.jsx
src/pages/RepoPage.jsx
src/pages/TagPage.jsx

cleanup
Closes #94 
```release-note
```

Fixed title and description in tag screen

---

src/__tests__/TagPage/HistoryLayers.test.js
src/components/HistoryLayers.jsx
src/components/TagDetails.jsx

…ch layer
cleanup
feature
Closes #100 
Closes #90 
```release-note
```

Changed name for dependencies tabs and added the layers hashes

---

src/__tests__/RepoPage/Repo.test.js
src/__tests__/TagPage/TagDetails.test.js
src/components/HistoryLayers.jsx
src/components/PreviewCard.jsx
src/components/RepoDetails.jsx
src/components/RepoDetailsMetadata.jsx
src/components/TagDetails.jsx

cleanup
feature 
Closes #101 
Closes #109 
```release-note
```

Renamed some details and added dropdown for pull image

---

src/__tests__/TagPage/VulnerabilitiesDetails.test.js
src/api.js
src/components/TagDetails.jsx
src/components/VulnerabilitiesDetails.jsx

bug
Closes #111 
Closes #117 
Fixing CVEList request, removing id/title from vulnerability card
```release-note
- Updated display of vulnerability card
```
By submitting this pull request, I confirm that my contribution is made under the terms of the …

fix: fixed cvelist request params, removed id/title from vulnerabiliy card

---

src/api.js

fix: repo query pagination params

---

src/api.js
src/components/DependsOn.jsx
src/components/Explore.jsx
src/components/Home.jsx
src/components/IsDependentOn.jsx
src/components/RepoCard.jsx
src/utilities/objectModels.js

cleanup
Closes #34 
```release-note
```

Updated repo cards to include download counter

---

src/App.css
src/__tests__/RepoPage/Tags.test.js
src/api.js
src/components/RepoDetails.jsx
src/components/Tags.jsx

bug
Closes #133 
```release-note
```

Fixed the bug regarding published date for images in Tag Page

---

src/__tests__/TagPage/TagDetails.test.js
src/components/PreviewCard.jsx
src/components/RepoCard.jsx
src/components/RepoDetailsMetadata.jsx
src/components/TagDetails.jsx
src/components/Tags.jsx
src/host.js

feature, bug
Closes #127 
Closes #138 
Closes #140 
Closes #143 
Fixes all overflowing text to default to ellipsis where it was missing.
Adds tooltip on hover for all overflow-prone text
Fixed pullstrings for images by removing http/s protocol from hostname
**Does this PR introduce any user-facing …

feat: Added tooltip for text prone to overflow, fixed pullstrings

---

src/components/SearchSuggestion.jsx

cleanup
Closes #142 
Implemented failed(responded with no results) search state, currently displayed as red border around search input
```release-note
- Search input colored red if search failed(responded with no results)
```
By submitting this pull …

patch: change search border color if search failed(responded with no results)

---

public/index.html

bug
Closes #130 
```release-note
```

fix favicon ref

---

src/__tests__/TagPage/VulnerabilitiesDetails.test.js
src/components/HistoryLayers.jsx
src/components/VulnerabilitiesDetails.jsx

cleanup/bug
Closes #152 
Change display for description/fixed in for CVE cards, fix overflow issue
```release-note
- Updated display of dropdowns in VulnerabilityCard
```
By submitting this pull request, I confirm that my contribution is made under the …

fix: dropdown text and overflow fix for CVE Card

---

src/components/RepoCard.jsx
src/components/RepoDetailsMetadata.jsx
src/components/TagDetailsMetadata.jsx
src/components/Tags.jsx

…with the timestam
bug
Closes #136 
```release-note
```

Updated the push date format to weeks, days, hours and added tooltip for timestamp

---

package-lock.json
package.json
src/__tests__/TagPage/DependsOn.test.js
src/__tests__/TagPage/IsDependentOn.test.js
src/api.js
src/components/DependsOn.jsx
src/components/IsDependentOn.jsx
src/components/RepoCard.jsx
src/components/RepoDetails.jsx
src/components/RepoDetailsMetadata.jsx
src/components/TagCard.jsx
src/components/TagDetails.jsx
src/components/TagDetailsMetadata.jsx
src/components/Tags.jsx

Added license info to repodetails and tagdetails
Added md parsing for relevant fields
Cleaned up uses/used by tabs
!Added dependency - update local packages after merge
feature/cleanup/bug
Closes #149 
Closes #160 
Closes #161
```release-note
- Added …
```

feat: License Data, MD support, usedby/uses cleanup

---

src/components/TagCard.jsx

bug
Closes #167 
Fixed navigation of tag cards
```release-note
```

fix: Tag card navigation to tag page

---

src/components/RepoCard.jsx
src/components/RepoDetailsMetadata.jsx
src/components/TagCard.jsx
src/components/TagDetailsMetadata.jsx
src/utilities/MarkdowntojsxWrapper.jsx

Feature/cleanup
Closes #169 
Extended the markdown parser implementation with our own custom wrapper that allows us to define global configuration overrides, such as links always opening in a new tab
```release-note
```
By submitting this pull request, I …

feat: Implemented wrapper for md parser so we can pass custom options

---

src/__tests__/Shared/SearchSuggestion.test.js
src/components/PreviewCard.jsx
src/components/RepoCard.jsx
src/components/RepoDetails.jsx
src/components/SearchSuggestion.jsx
src/components/TagDetails.jsx

cleanup
Closes #179 
Adds icons to search suggestions, updated logo styles across app
```release-note
- Image logos appear in search suggestions
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

patch: Icons in search bar, updated icon styles

---

src/__tests__/Shared/SearchSuggestion.test.js
src/api.js
src/components/Explore.jsx
src/components/SearchSuggestion.jsx
src/utilities/objectModels.js

feature, cleanup
Closes #178 
Implements tag search feature in the searchbar. Added search hints when search input is focused but nothing is typed. Lowered the minimum search query length to 1 character. 
Reordered filters on Explore page and renamed "Image" filters to "Additional filters"
**Does this PR …

feat: Implemented tag search, added search hints, reordered filters

---

src/components/TagCard.jsx

cleanup
Closes #183
Closes #181 
Updated capitalization on manifest table in tagcard
```release-note
```

fix: Updated capitalization on tagCard

---

src/components/Home.jsx

cleanup
Closes #185 
```release-note
```

fix: Renamed from recently updated repositories to recently updated images

---

src/__tests__/TagPage/TagDetails.test.js
src/components/TagDetails.jsx
src/utilities/pullStrings.js

cleanup
Closes #182 
Fixed various small issues with pullstring dropdown on image page, refactored pullstrings to utilities module.
Added snackbar to provide user feedback on copy
```release-note
- Snackbar added to provide user feedback on copy of …
```

fix: Fixed issues with pullstring dropdown, added snackbar on copy

---

src/__tests__/Explore/Explore.test.js
src/__tests__/HomePage/Home.test.js
src/__tests__/RepoPage/Repo.test.js
src/__tests__/TagPage/TagDetails.test.js
src/components/PreviewCard.jsx
src/components/RepoCard.jsx
src/components/RepoDetails.jsx
src/components/TagDetails.jsx
src/components/VulnerabilitiesDetails.jsx
src/utilities/vulnerabilityAndSignatureCheck.js
src/utilities/vulnerabilityAndSignatureComponents.jsx

cleanup 
Closes #170 
Closes #189 
```release-note
```

Refactored and minimised the signatures and vulnerabilities

---

src/components/SearchSuggestion.jsx

bug
Closes #193 
```release-note
```

fix: added border radius to search input wrapper

---

src/components/Home.jsx
src/components/RepoCard.jsx

bugfix
Closes #201
Closes #202 
```release-note
```

Fix: changed popular cards to large cards, increased space alloted for repo name

---

src/components/Header.jsx

bug
Closes #196 
```release-note
```

Fixed the logo aspect

---

src/components/TagDetails.jsx

bug
Closes #208 
```release-note
```

Aligned the pull section

---

src/components/VulnerabilitiesDetails.jsx

bug
Closes #198 
Fixes infinite load on vulnerability tab
```release-note
```

fix: Fixed loading logic for vulnerability tab

---

src/__tests__/TagPage/TagDetails.test.js
src/api.js
src/components/Explore.jsx
src/components/Home.jsx
src/components/PreviewCard.jsx
src/components/RepoCard.jsx
src/components/RepoDetails.jsx
src/components/TagDetails.jsx
src/utilities/vulnerabilityAndSignatureCheck.js
src/utilities/vulnerabilityAndSignatureComponents.jsx

cleanup
Closes #195 
```release-note
```

fix: updated unknown vulnerability logic

---

src/__tests__/Explore/Explore.test.js
src/api.js
src/components/Explore.jsx
src/utilities/sortCriteria.js

feature/cleanup
Closes #205 
Closes #216
Implemented search feature on explore page. 
Fixed small ux positioning for Results count
```release-note
- Sorting the search results is implemented!
```
By submitting this pull request, I confirm that my …

feat: Implemented sorting on search page

---

src/components/HistoryLayers.jsx
src/components/TagCard.jsx
src/components/TagDetails.jsx

Cleaned up the alignement on the ui

---

src/components/TagDetails.jsx

bug
Closes #226 
```release-note
```

fix: pull image dropdown width

---

src/components/RepoCard.jsx

cleanup
#207 
```release-note
```

Changed the hover of the repo card

---

package-lock.json
package.json
src/components/Explore.jsx

feature
Closes #222 
```release-note
```

Made the filters sticky

---

src/components/SignIn.jsx
src/pages/LoginPage.jsx

cleanup
Closes #238
Better hide the login page while it is loading to check auth configuration on the zot instance
```release-note
```

Hide signin page while loading

---

src/__tests__/RepoPage/Tags.test.js
src/components/Tags.jsx

Feature
Closes #246 
Allows for filtering of tags in the tags tab. Implemented through local filtering currently as back-end support for this use case is still in discussion.
```release-note
- Added text filter for the tags tab
```
By submitting this pull …

feat: Added filter for tags tab

---

src/components/Home.jsx

cleanup
Closes #251 
```release-note
```

Most popular title changes

---

src/__tests__/Explore/Explore.test.js
src/__tests__/RepoPage/Repo.test.js
src/__tests__/TagPage/TagDetails.test.js
src/utilities/vulnerabilityAndSignatureCheck.js
src/utilities/vulnerabilityAndSignatureComponents.jsx

feature
Closes #245 
```release-note
```

Added failed scan chip

---

src/__tests__/RepoPage/Tags.test.js
src/components/Tags.jsx
src/utilities/sortCriteria.js

feature
Closes #258 
Adds sorting option to the tags tab in repoDetails page
```release-note
- Tags can now be sorted in the repoDetails page
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

feat:Added tags sort filter

---

src/__tests__/TagPage/TagDetails.test.js
src/components/TagDetails.jsx

feature
Closes #243 
```release-note
```

Updated the pull image button according to the mockups

---

src/__tests__/TagPage/DependsOn.test.js
src/__tests__/TagPage/IsDependentOn.test.js
src/__tests__/TagPage/TagDetails.test.js
src/api.js
src/components/DependsOn.jsx
src/components/IsDependentOn.jsx
src/utilities/objectModels.js

patch
Closes #276 
Updates zui usage of updated zot queries.
Implements pagination of results on uses and used by tabs on tag detail page
```release-note
```

patch: based derived update

---

public/index.html
src/App.js
src/components/SignIn.jsx
src/pages/LoginPage.jsx

bug
Closes #281 
Fixes the bug which didn't allow direct browser navigation within zui, such as using the browser back button or directly inputing a specific zui page in the browser address bar. Previously, any navigation outside of the in-app navigation redirected to home.
**Does this PR introduce any …

fix: fixed external navigation bug

---

src/__tests__/TagPage/ReferredBy.test.js
src/__tests__/TagPage/TagDetails.test.js
src/api.js
src/components/DependsOn.jsx
src/components/Header.jsx
src/components/ReferredBy.jsx
src/components/ReferrerCard.jsx
src/components/TagDetails.jsx
src/utilities/objectModels.js

Added the references tab to the tag details page
feature
Closes #282 
```release-note
```

References tab

---

src/components/VulnerabilitiesDetails.jsx

fix: infinite loading bug on cve fix

---

src/__tests__/TagPage/DependsOn.test.js
src/__tests__/TagPage/IsDependentOn.test.js
src/__tests__/TagPage/TagDetails.test.js
src/components/DependsOn.jsx
src/components/IsDependentOn.jsx

bug
Closes #290 
Fixes infinite loading bug on "uses" tab in image details page
```release-note
```

fix: infinite loading bug

---

src/App.css
src/App.js
src/api.js
src/components/Login/SignIn.jsx
src/utilities/AuthWrapper.jsx

cleanup
Closes #295 
Removes unfinished implementations from main branch to prepare for RC
```release-note
```

fix: cleanup unfinished implementations for RC

---

src/components/Repo/RepoDetails.jsx
src/components/Tag/TagDetails.jsx
src/utilities/AuthWrapper.jsx

bug
Closes #297 
Fixes bug where sometimes you couldn't scroll all the way to the bottom of the page, thus cutting off content
```release-note
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

fix: page sometimes being cut off before all content shown

---

src/components/Header/SearchSuggestion.jsx

bug
Closes #300 
Fixes the weird behaviour detailed in the issue
```release-note
```

fix: fix search query change on explore

---

src/components/Tag/Tabs/VulnerabilitiesDetails.jsx

fix: fixed in tags not wrapping correctly

---

public/index.html
src/__tests__/RepoPage/Repo.test.js
src/__tests__/Shared/RepoCard.test.js
src/api.js
src/components/Explore/Explore.jsx
src/components/Explore/FilterDialog.jsx
src/components/Header/Header.jsx
src/components/Repo/RepoDetailsMetadata.jsx
src/components/Shared/FilterCard.jsx
src/components/Shared/RepoCard.jsx
src/components/Shared/TagCard.jsx
src/components/Tag/TagDetailsMetadata.jsx

Cleanup
Closes #307 
Fix zap scan warnings caused by the ui
```release-note
```

fix: fix zap scan warnings

---

src/__tests__/RepoPage/Tags.test.js
src/__tests__/TagPage/TagDetails.test.js
src/api.js
src/components/Header/SearchSuggestion.jsx
src/components/Repo/RepoDetails.jsx
src/components/Repo/Tabs/Tags.jsx
src/components/Shared/RepoCard.jsx
src/components/Shared/TagCard.jsx
src/components/Tag/Tabs/DependsOn.jsx
src/components/Tag/Tabs/IsDependentOn.jsx
src/components/Tag/TagDetails.jsx
src/utilities/objectModels.js
src/utilities/sortCriteria.js

feature
Closes #312 
Adds multi-arch features
```release-note
- cleanup platform chips for multiarch images
- on Tag page, you can now select which os/arch you want the image for, if supported
- In the Tags tab of the Repo page, all the manifests of the image are displayed in the dropdown of the TagCard …
```

feat: multi-arch image features

---

.github/workflows/end-to-end-test.yml
.gitignore
Makefile
tests/data/config.yaml
tests/scripts/load_test_data.py
tests/scripts/pull_update_push_image.sh

ci(tests): add a new workflow for running integration tests against a zot server

---

tests/scripts/load_test_data.py
tests/scripts/pull_update_push_image.sh

ci(tests): some updates to the scripts to make them work better on macos

---

src/__tests__/TagPage/VulnerabilitiesDetails.test.js
src/api.js
src/components/Explore/Explore.jsx
src/components/Tag/Tabs/VulnerabilitiesDetails.jsx

feature
Closes #323 
Adds a text filter for the CVE List tab
```release-note
- Vulnerabilities tab now contains a search input
```

feat: cve list filtering

---

src/components/Repo/RepoDetails.jsx
src/components/Shared/RepoCard.jsx
src/components/Tag/TagDetails.jsx

patch
Closes #328 
Make placeholder logos static, so they don't change on every rerender
```release-note
```

patch: update placeholder image logic

---

.github/workflows/end-to-end-test.yml
tests/scripts/load_test_data.py
tests/scripts/pull_update_push_image.sh

test(end-to-end): provide CVE information for the tests to consume

---

src/__tests__/Explore/FilterCard.test.js
src/components/Explore/Explore.jsx
src/components/Home/Home.jsx
src/components/Shared/FilterCard.jsx
src/components/Shared/RepoCard.jsx
src/index.js

patch
Closes #332 
Updates design on the explore page to match new ux goals
```release-note
```

patch: explore page ux updates

---

src/__tests__/TagPage/TagDetails.test.js
src/components/Explore/Explore.jsx
src/components/Repo/RepoDetails.jsx
src/components/Repo/RepoDetailsMetadata.jsx
src/components/Shared/LayerCard.jsx
src/components/Shared/PullCommandButton.jsx
src/components/Shared/RepoCard.jsx
src/components/Tag/Tabs/DependsOn.jsx
src/components/Tag/Tabs/HistoryLayers.jsx
src/components/Tag/Tabs/IsDependentOn.jsx
src/components/Tag/Tabs/VulnerabilitiesDetails.jsx
src/components/Tag/TagDetails.jsx
src/components/Tag/TagDetailsMetadata.jsx
src/pages/TagPage.jsx

patch
Closes #334 
Updates the design of the tag details page
```release-note
- Updated the tag details page to match new design
- Updated the sub-components used in the tag details page tabs to match new design
- Refactored and redesigned the "pull image" widget into a separate component used inside the …
```

patch: tag page design updates

---

src/__tests__/RepoPage/Tags.test.js
src/__tests__/TagPage/VulnerabilitiesDetails.test.js
src/components/Repo/RepoDetails.jsx
src/components/Repo/Tabs/Tags.jsx
src/components/Shared/TagCard.jsx
src/components/Shared/VulnerabilityCard.jsx
src/components/Tag/Tabs/DependsOn.jsx
src/components/Tag/Tabs/HistoryLayers.jsx
src/components/Tag/Tabs/IsDependentOn.jsx
src/components/Tag/Tabs/ReferredBy.jsx
src/components/Tag/Tabs/VulnerabilitiesDetails.jsx
src/components/Tag/TagDetails.jsx

patch/cleanup
Closes #344 
Update visual design of vulnerabilities module, and some additional styling code cleanup
```release-note
- Updated appearance of the cve cards
- Updated appearance of the vulnerabilities tab
- Refactored VulnerabilityCard component as individual component for reusability
```
By …

patch: updated vulnerability design, styling cleanup

---

tests/scripts/pull_update_push_image.sh

test(test-data): add layers information to the image metadata json

---

.github/workflows/end-to-end-test.yml
.gitignore
Makefile
package-lock.json
package.json
playwright.config.js
tests/data/config.yaml
tests/explore.spec.js
tests/home.spec.js
tests/navbar.spec.js
tests/repo.spec.js
tests/scripts/pull_update_push_image.sh
tests/tag.spec.js
tests/utils/scroll.js
tests/utils/test-data-parser.js
tests/values/test-constants.js

feat:Integration tests

---

src/api.js
src/components/Shared/VulnerabilityCard.jsx
src/components/Tag/Tabs/VulnerabilitiesDetails.jsx
src/components/Tag/TagDetails.jsx

- updated CVEListForImage api calls
- updated ImageListWithCVEFixed api calls
- now cves are shown for specific tag
- fixed tags now only shows tags that match platform with current digest
- moved platform selector on tagdetails page
Closes #356 
Closes #368

patch: update cve api usage

---

src/api.js

See: https://github.com/project-zot/zot/issues/1883

feat: add prefix zot to /auth urls

---

.github/workflows/dco.yml

ci: dco job should also run on PRs

---

src/components/Header/Header.jsx

fix: update zot documentation urls

---

src/__tests__/TagPage/VulnerabilitiesDetails.test.js
src/components/Tag/Tabs/VulnerabilitiesDetails.jsx

fix: change 'csv' to 'CSV' in the vulnerabilities download options list

---

playwright.config.js
src/__tests__/TagPage/VulnerabilitiesDetails.test.js
src/api.js
src/components/Shared/VulnerabilityCountCard.jsx
src/components/Tag/Tabs/VulnerabilitiesDetails.jsx

feat: add cve summary in vulnerability tab

---

.github/workflows/end-to-end-test.yml
src/__tests__/TagPage/VulnerabilitiesDetails.test.js
src/components/Shared/VulnerabilityCard.jsx
src/components/Tag/Tabs/VulnerabilitiesDetails.jsx

fix(cve): make cards collapsed by default

---

src/__tests__/TagPage/VulnerabilitiesDetails.test.js
src/api.js
src/components/Shared/VulnerabilityCountCard.jsx
src/components/Tag/Tabs/VulnerabilitiesDetails.jsx

feat(cve): filter cves by severity

---

package-lock.json
package.json

chore: fix dependabot alerts

---

src/components/Login/SignIn.jsx

feature
Re-enables button for logging in with GitLab.
On my own install I use GitLab, and while enabling the GitLab OAuth provider was seamless, the lack of a login button made it cumbersome.
Tested by building zot with my own zui repo and running, check https://zot.twingine.com
```release-note
- Added …
```

Re-enable GitLab OAuth login.
