project-zot/zui

- src/components/Explore.jsx
- src/components/Home.jsx
- src/components/RepoDetails.jsx
- src/components/SignIn.jsx
- src/constants.js
- src/host.js
For development, auto needs to be disabled and hostname manually configured
Modified name of host config file.
feature
Closes #58 
For production purposes added option to automatically use zui's url origin as hostname for requests, for when zot is deployed together with zui
no
> Added host config to automatically use origin as hostname.

- src/__tests__/Shared/PreviewCard.test.js
- src/__tests__/Shared/RepoCard.test.js
- src/api.js
- src/components/PreviewCard.jsx
- src/components/RepoCard.jsx
- src/components/RepoDetails.jsx
- src/components/RepoDetailsMetadata.jsx
feature
Closes #32 
Consumes new zot ExpandedRepoInfo endpoint extensions.
Updated relevant tests
Depends on latest version of zot
```release-note
- Updated Repo Details component to use platforms returned by api to generate platform chips
- Updated styling in Repo Details component to newest mocks
- Updated styling in RepoMetadata component to match newest mocks
- Updated data displayed in RepoMetadata component to use real data returned from api
```
By submitting this pull request, I confirm that my …
> Updated repo details component to consume new ExpandedRepoInfo api changes

- src/__tests__/Explore/Explore.test.js
- src/__tests__/HomePage/Home.test.js
- src/api.js
- src/components/Explore.jsx
- src/components/Home.jsx
Signed-off-by: Amelia-Maria Breda <ameliamaria.breda@dxc.com>
ui
Closes #31
Update front-end code to leverage RepoSummary returned by ImageListWithLatestTag
Depends on latest version of zot
```release-note
```
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> Updated front-end code to replace ImageListWithLatestTag with RepoListWithNewestImage

- src/__tests__/TagPage/TagDetails.test.js
- src/__tests__/TagPage/VulnerabilitiesDetails.test.js
- src/api.js
- src/components/HistoryLayers.jsx
- src/components/RepoDetails.jsx
- src/components/TagDetails.jsx
- src/components/TagDetailsMetadata.jsx
- src/components/VulnerabilitiesDetails.jsx
feature
Closes #107 
Implements feature in the vulnerability tab of the TagDetails page that shows in which version is each particular CVE fixed
Fixed call logic for TagDetails page, changed to the Image query.
```release-note
- Added section in vulnerabilityCard that displays what tags fix the cve
```
> feat: Implemented fixed-in, fixed TagDetails page query

- src/__tests__/Explore/FilterCard.test.js
- src/api.js
- src/components/Explore.jsx
- src/components/FilterCard.jsx
feature
Closes #118 
Updated filter logic on Explore page to match the new backend implementation of allowing multiple filters to be selected
```release-note
- Multiple filters from the same category are now supported on explore page
```
By submitting this …
> fix: Updated filter logic to match multi-filter implementation in backend

- src/components/RepoCard.jsx
- src/components/RepoDetails.jsx
- src/components/RepoDetailsMetadata.jsx
- src/components/TagDetails.jsx
- src/components/Tags.jsx
cleanup
Closes #125 
Closes #128 
```release-note
```
> Removed 'Quickstart' and added for each N/A the property that we don't have data for in ui 

- src/__tests__/Shared/RepoCard.test.js
- src/__tests__/TagPage/DependsOn.test.js
- src/__tests__/TagPage/IsDependentOn.test.js
- src/api.js
- src/components/DependsOn.jsx
- src/components/Explore.jsx
- src/components/HistoryLayers.jsx
- src/components/Home.jsx
- src/components/IsDependentOn.jsx
- src/components/RepoDetailsMetadata.jsx
- src/components/VulnerabilitiesDetails.jsx
cleanup
Closes #124 
Closes #129 
Updated used by/uses tabs to use cards and removed unnecessary parts of ui
```release-note
- Removed unnecessary text in uses and used by tabs on image page
- Changed display of used used by images to cards instead of text …
```
> fix: Change display of uses/used by, cleanup repocard usage

- src/__tests__/TagPage/VulnerabilitiesDetails.test.js
- src/components/VulnerabilitiesDetails.jsx
cleanup
Closes #145 
Added user interaction in order to fetch and display tags with cve fixed
```release-note
- Updated display of fixed tags on CVE cards
```
> fix: Added logic to get fixed tags only on user action

- src/components/FilterCard.jsx
- src/utilities/filterConstants.js
cleanup
Closes #112 
Changed display labels of filters on Explore page to match Architectures described in the GOARCH document, with the detailed version displayed on hover
```release-note
- Updated explore page filters labels
- Added tooltip with more …
```
> patch: Changed display values of filters, added tooltip on hover

- src/components/SearchSuggestion.jsx
bug
Closes #168 
Search fail state should be removed on input change regardless if backend query is made
```release-note
```
> fix: changed search fail state to update regardless if query made

- src/__tests__/RepoPage/Tags.test.js
- src/components/TagCard.jsx
- src/utilities/MarkdowntojsxWrapper.jsx
Also updated md parser config
cleanup
Closes #166 
Updated display of digest dropdown on TagCard
```release-note
- Updated display of digest dropdown in tag card to match vulnerability card dropdowns
```
By submitting this pull request, I confirm that my …
> patch: Added arrow to digest dropdown

- public/index.html
- src/utilities/filterConstants.js
cleanup
Closes #165 
Updated labels for os filters, updated app title and description
```release-note
```
> fix: changed Title, desc, changed label for OS filters

- src/__tests__/Explore/Explore.test.js
- src/__tests__/HomePage/Home.test.js
- src/__tests__/RepoPage/Repo.test.js
- src/__tests__/TagPage/DependsOn.test.js
- src/__tests__/TagPage/IsDependentOn.test.js
- src/__tests__/TagPage/TagDetails.test.js
- src/api.js
- src/components/DependsOn.jsx
- src/components/Explore.jsx
- src/components/Home.jsx
- src/components/IsDependentOn.jsx
- src/components/PreviewCard.jsx
- src/components/RepoCard.jsx
- src/components/RepoDetails.jsx
- src/components/TagDetails.jsx
- src/utilities/objectModels.js
cleanup
feature
Closes #151 
```release-note
```
> Added vulnerabilities in RepoCard, PreviewCard, RepoDetails and TagDetails with uses and used by tabs

- src/__tests__/Explore/Explore.test.js
- src/__tests__/RepoPage/Repo.test.js
- src/__tests__/TagPage/TagDetails.test.js
- src/utilities/vulnerabilityAndSignatureCheck.js
cleanup
Closes #195 
Temporary fix for #195, the larger logic of which chip to hide and show when the backend returns a "UNKNOWN" severity still needs follow-up
```release-note
```
By submitting this pull request, I confirm that my contribution is made …
> fix: hide unknown vulnerability

- src/components/SearchSuggestion.jsx
bug
Closes #197 
Changed loading/failed/open state logic in searchSuggestion component to fix issues stemming from user actions being too fast
```release-note
```
By submitting this pull request, I confirm that my contribution is made under the terms of …
> fix: Fixed empty query string if user types fast

- src/utilities/sortCriteria.js
bug
Temporarily remove the sort criteria of most starred, as starring an image is not yet implemented.
```release-note
```
> fix: temporarily remove star sorting criteria

- src/App.css
- src/components/Header.jsx
feature
Closes #223 
```release-note
```
> Header is rendered when user starts scrolling up

- src/__tests__/Explore/Explore.test.js
- src/__tests__/Explore/FilterCard.test.js
- src/__tests__/HomePage/Home.test.js
- src/__tests__/RepoPage/Repo.test.js
- src/__tests__/Shared/RepoCard.test.js
- src/api.js
- src/components/Explore.jsx
- src/components/FilterCard.jsx
- src/components/Home.jsx
- src/components/RepoCard.jsx
- src/components/RepoDetails.jsx
feature
Closes #234 
Closes #240 
Added support on explore page for preselected filter/sorting order. 
Added logic for clicking OS/Arch chips to redirect to search with the preselected filter
Added view all buttons for the homepage sections to redirect with preselected sort order
**Does this PR introduce …
> feat: implemented support for preselected sort order and filters

- src/__tests__/RepoPage/Tags.test.js
- src/components/Tags.jsx
cleanup
Closes #257 
Update design of tags search
```release-note
- New tags search design
```
> patch: tags filter design

- src/components/SearchSuggestion.jsx
feature
Closes #263 
```release-note
```
> Pointer cursor on search suggestions

- src/components/Explore.jsx
- src/components/FilterCard.jsx
bug
Closes #255 
Fixes a bug with preselecting sort order from homepage
```release-note
```
> fix: preselected sort double first page fix

- src/utilities/MarkdowntojsxWrapper.jsx
bug
Closes #269 
Markdown-to-jsx compiles some markdown using \<p\> tags, which we want to avoid as this generates invalid html in some instances (\<p\> as a descendant of another \<p\>)
```release-note
```
By submitting this pull request, I confirm that …
> fix: Provide p tag override to avoid md parsing errors

- src/__tests__/TagPage/HistoryLayers.test.js
- src/components/HistoryLayers.jsx
- src/components/LayerCard.jsx
feature
Closes #261
Implements the new version of the layer history tab on the tag detail page
```release-note
```
> patch: new layer history version implementation

- src/__tests__/TagPage/VulnerabilitiesDetails.test.js
- src/api.js
- src/components/TagDetails.jsx
- src/components/VulnerabilitiesDetails.jsx
- src/utilities/objectModels.js
Feature
Closes #284 
Integrates the new CVEListForImage query pagination changes into the ui
```release-note
```
> patch: integrated pagination in cve tab

- .github/workflows/build-test.yml
Also update some of the plugins we use in the build-test.yml workflow.
Enable cache for npm dependencies in the build-test.yml workflow.
Signed-off-by: Andrei Aaron <aaaron@luxoft.com>
> ci: publish zui build as part of the release workflow

- src/__tests__/RepoPage/Repo.test.js
- src/__tests__/TagPage/TagDetails.test.js
- src/components/Repo/RepoDetails.jsx
- src/components/Tag/TagDetails.jsx
bug
Closes #305 
If the user lands on the page of a repo or a tag that doesn't exist, for example, by changing the url directly, the app will redirect the use back to the home page
```release-note
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> fix: redirect to home if data invalid on repo or tag page

- .github/workflows/build-test.yml
We will reference these builds in the zot repo for testing the integration.
> ci(releases): publish build results for every commit on main branch

- src/__tests__/TagPage/DependsOn.test.js
- src/__tests__/TagPage/HistoryLayers.test.js
- src/__tests__/TagPage/IsDependentOn.test.js
- src/__tests__/TagPage/TagDetails.test.js
- src/api.js
- src/components/Header/SearchSuggestion.jsx
- src/components/Repo/Tabs/Tags.jsx
- src/components/Tag/Tabs/DependsOn.jsx
- src/components/Tag/Tabs/HistoryLayers.jsx
- src/components/Tag/Tabs/IsDependentOn.jsx
- src/components/Tag/TagDetails.jsx
- src/utilities/objectModels.js
patch
Closes #313 
zot's new multi-arch support has breaking changes to the graphQL search extension. zui's usage needs to be updated accordingly
```release-note
```
> patch: Update API usage for multi-arch support

- src/__tests__/TagPage/ReferredBy.test.js
- src/api.js
- src/components/Tag/Tabs/ReferredBy.jsx
- src/components/Tag/TagDetails.jsx
- src/utilities/objectModels.js
patch
Closes #326 
Updates zui's usage of the backend API to consume referrers from the image query as opposed to making a separate query for the referrers
```release-note
```
> patch: referrers from image query

- .github/workflows/end-to-end-test.yml
> build(go): upgrade go version used in end-to-end tests to 1.20

- src/components/Tag/Tabs/HistoryLayers.jsx
bug
Closes project-zot/zot#1417
Fixed bug causing layer history not to update for multiarch images when switching between platforms
```release-note
```
> fix: fixed layer history not updating for multiarch images

- src/components/Login/SignIn.jsx
- tests/tag.spec.js
> fix: login bug when both anonymous and auth is enabled

- src/utilities/vulnerabilityAndSignatureComponents.jsx
bug
Closes #370 
```release-note
```
> fix: Update tooltip for vulnerability chips

- tests/explore.spec.js
- tests/home.spec.js
- tests/navbar.spec.js
- tests/repo.spec.js
- tests/tag.spec.js
patch
patch integration tests
```release-note
```
> patch: update integration tests

- src/components/Login/SignIn.jsx
- src/components/Login/ThirdPartyLoginComponents.jsx
feature
This PR allow usage of generic OIDC with customizable name (linked to zot https://github.com/project-zot/zot/pull/1691)
Won't break on upgrade / downgrades
no
If enabled on backend, it allows the display of a customizable login button
> feat: add customizable generic oidc login button

- src/__tests__/Shared/RepoCard.test.js
- src/api.js
- src/components/Explore/Explore.jsx
- src/components/Home/Home.jsx
- src/components/Repo/RepoDetails.jsx
- src/components/Shared/RepoCard.jsx
- src/components/Shared/SignatureTooltip.jsx
- src/components/Tag/TagDetails.jsx
- src/utilities/objectModels.js
- src/utilities/vulnerabilityAndSignatureCheck.jsx
- src/utilities/vulnerabilityAndSignatureComponents.jsx
feature
Closes #374 
Display advanced signature information in zui. Design still WIP
```release-note
```
> feat: Update signature integration to display extra info

- .github/workflows/end-to-end-test.yml
> ci(space): free up disk space before running tests

- src/components/Shared/SignatureTooltip.jsx
- src/utilities/objectModels.js
- src/utilities/vulnerabilityAndSignatureComponents.jsx
> fix: fixed display of new signature tooltips in some cases

- src/components/Home/Home.jsx
- tests/values/test-constants.js
Update usage of nodata component on homepage
```release-note
```
> patch: update nodata display on homepage

- src/utilities/vulnerabilityAndSignatureComponents.jsx
> feat: vulnerability chips - show icon before string

- src/components/Header/SearchSuggestion.jsx
> fix: show a loading message while waiting for a response

- src/__tests__/RepoPage/Tags.test.js
- src/api.js
- src/components/Repo/RepoDetails.jsx
- src/components/Repo/Tabs/Tags.jsx
- src/components/Shared/DeleteTag.jsx
- src/components/Shared/DeleteTagConfirmDialog.jsx
- src/components/Shared/TagCard.jsx
- src/utilities/objectModels.js
- tests/values/test-constants.js
> feat: added button to delete tag

- package-lock.json
- package.json
- src/__tests__/TagPage/VulnerabilitiesDetails.test.js
- src/api.js
- src/components/Tag/Tabs/VulnerabilitiesDetails.jsx
- src/utilities/objectModels.js
> feat: export vulnerabilities list

- src/__tests__/Explore/FilterCard.test.js
- src/utilities/filterConstants.js
- tests/explore.spec.js
feature
#407 
It is useful to be able to filter by OS and I typically have both linux and freebsd images in my repositories.
Ad-hoc testing with zot. I added a test for filtering for freebsd, similar to windows but haven't managed to run that test locally. Hopefully CI will work though.
I modified the 'explore filtering' test to add checks for freebsd as a filter.
No and no.
No
The user will see freebsd …
> feat: add freebsd as an OS filter (#407)

- src/__tests__/TagPage/VulnerabilitiesDetails.test.js
- src/components/Shared/VulnerabilityCard.jsx
- src/components/Tag/Tabs/VulnerabilitiesDetails.jsx
- tests/tag.spec.js
> feat: add expand/collapse view list buttons for vulnerabilities

- src/__tests__/TagPage/VulnerabilitiesDetails.test.js
- src/components/Tag/Tabs/VulnerabilitiesDetails.jsx
> fix(export vuln): change sheet name and download options name

- src/__tests__/TagPage/VulnerabilitiesDetails.test.js
- src/api.js
- src/components/Shared/VulnerabilityCard.jsx
- src/components/Tag/Tabs/VulnerabilitiesDetails.jsx
- src/utilities/objectModels.js
- tests/tag.spec.js
https://github.com/project-zot/zui/issues/405
https://github.com/project-zot/zui/issues/394
```release-note
```
> feat(cve): add more information

- src/__tests__/TagPage/VulnerabilitiesDetails.test.js
- src/api.js
- src/components/Shared/VulnerabilityCard.jsx
- src/components/Shared/VulnerabilityPackageSection.jsx
- src/components/Tag/Tabs/VulnerabilitiesDetails.jsx
- src/utilities/objectModels.js
feature
Towards https://github.com/project-zot/zot/issues/2175
This PR displays the Package Path information for the package list for a given CVE in the vulnerabilities list.
Since there is more data being displayed, this PR also brings in a change to display this information in a vertically stacked form with a separate section for each affected package.
References #426 
Screenshots:
CSV export:
```
id,severity,title,description,reference,packageName,packagePath,packageInstalledVersion,packageFixedVersion
CVE-2016-1000027,CRITICAL,spring: HttpInvokerServiceExporter readRemoteInvocation method untrusted java deserialization,"Pivotal Spring Framework …
```
> feat(cve): include PkgPath information in image cve UI list using sections and in CVE export

- src/__tests__/Explore/Explore.test.js
- src/__tests__/HomePage/Home.test.js
- src/__tests__/RepoPage/Repo.test.js
- src/__tests__/TagPage/TagDetails.test.js
- src/components/Explore/Explore.jsx
- src/components/Home/Home.jsx
- src/components/Repo/RepoDetails.jsx
- src/components/Shared/PreviewCard.jsx
- src/components/Shared/RepoCard.jsx
- src/components/Shared/SignatureTooltip.jsx
- src/components/Tag/Tabs/DependsOn.jsx
- src/components/Tag/Tabs/IsDependentOn.jsx
- src/components/Tag/TagDetails.jsx
- src/utilities/filterConstants.js
- src/utilities/objectModels.js
- src/utilities/vulnerabilityAndSignatureCheck.jsx
- src/utilities/vulnerabilityAndSignatureComponents.jsx
- tests/utils/test-data-parser.js
> patch: signature display redesign

- src/__tests__/Header/UserAccountMenu.test.js
- src/components/Header/UserAccountMenu.jsx
bug
Closes #424 
This PR fixes a bug where 2 horizontal lines show up in the User Account menu when the API key setting is disabled.
With API keys disabled:
With API keys enabled:
N/A
Not expected to break upgrades or downgrades. Not tested on a cluster.
None
No
> fix: don't display divider for API Keys menu item when API key is disabled

- src/__tests__/LoginPage/SignIn.test.js
- src/components/Login/SignIn.jsx
papercut-fix
Closes #430 
This PR contains the following changes:
1. When a user presses the `Enter` button in the login page's username or password fields, it performs submit only if both username and password fields have some data in them (neither of them are blank).
2. Adds and modifies unit tests to cover the behavior.
3. Removes props that are not used by the `SignIn` component from test cases.
4. Fixes a typo in `data-testid` for the OpenID Divider to avoid an error being shown in the Unit Test runs.
Pressing Enter on a fresh login page:
Pressing Enter on the username field while password is blank:
Pressing Enter on the password field while …
> papercut-fix: perform login on enter button press for basic auth in the login page

- tests/scripts/pull_update_push_image.sh
Avoid errors caused by downloads hitting http code 429, toomanyrequests, when downloading from official upstream repository
> chore: use our own trivy repository

- .github/workflows/end-to-end-test.yml
Artifact actions v3 will be closing down by January 30, 2025.
> chore: upgrade to actions/upload-artifact@v4

- tests/scripts/pull_update_push_image.sh
> fix: jq argument argfile was deprecated and removed

- .github/workflows/end-to-end-test.yml
- src/api.js
- src/components/Tag/TagDetails.jsx
- src/utilities/objectModels.js
- tests/values/test-constants.js
See https://github.com/project-zot/zui/issues/476
In previous implementations the referrers tab only showed the referrers returned at image level, ignoring the referrers returned at manifest level. This is fine for singlearch images, since they are the same. For images containing multiple manifests only index referrers were shown.
The current implementation would show both the referrers to the index and the current manifest.
> fix: show referrers pointing to image manifests
